# Generated by Django 2.1.2 on 2018-10-06 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20181006_1834'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='published_at',
            new_name='published',
        ),
    ]
