# Generated by Django 2.1.2 on 2018-10-16 22:20

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_scheduled_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata',
            name='payload',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=''),
            preserve_default=False,
        ),
    ]
