# Generated by Django 2.1.2 on 2018-10-17 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20181016_2356'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='metadata',
            unique_together=set(),
        ),
    ]
